### ISSUE TITLE
database connection failed

### ISSUE THREAD

**Issue by koo9** [apnar/docker-image-timetrex#1]
hi when running the init page, the database connection failed. is it because it's trying to connect to the postgresql on the local host but not on docker? the popup message reads "Connection test to your database as non-privileged user has Failed.  please correct your setting and try again"

**Comment by apnar** [comment]
The postgres database is in the same container.  Did the database get initialized?  What's in the database directory you're bind mounting? (is it still empty or did a postgres database get created there)

**Comment by koo9** [comment]
![dberror](https://user-images.githubusercontent.com/8421906/41881210-82f8f8fc-789f-11e8-931e-d6113aef8b85.PNG)
yes, it's in the same container. the first run on the ini.php should initialize the database. I used the default setting to run 
docker docker run -d \
           --name timetrex \
           -p 8080:80 \
           apnar/timetrex

so the database directory should be inside of the container.

**Comment by apnar** [comment]
I'd strongly recommend using the bind mounts for your database, storage, and ini file like in the example.  Otherwise if you remove your docker container you'll lose all your data.

Regardless, I'd expect it to work without.  The original postgres database initialization is done in the docker-entrypoint.sh script.  So hop in the container and look in the /database directory to see if it's getting created.  Once the postgres database is exists than the init.php page will add the timetrex parts.

**Comment by koo9** [comment]
btw, I am using docker on windows. looks like the parameter -v /docker/timetrex/timetrex.ini.php:/var/www/html/timetrex/timetrex.ini.php  does not work even thought I created the  /docker/timetrex/timetrex.ini.php file with the content from here https://github.com/apnar/docker-image-timetrex/blob/master/timetrex.ini.php.dist

**Comment by koo9** [comment]
this repo is for linux. not for windows. i see.

**Comment by apnar** [comment]
I've never tried it on windows, may work, may not.  You should look up how to do bind mounts on windows.  Quick google found this:

https://rominirani.com/docker-on-windows-mounting-host-directories-d96f3f056a2c

**Comment by koo9** [comment]
thx, will take a look.

**Comment by koo9** [comment]
![postgres](https://user-images.githubusercontent.com/8421906/41881954-8165a75c-78a3-11e8-9252-b69525f9e7d3.PNG)
looks like the database is there.

**Comment by apnar** [comment]
From that prompt in the container you can verify that you can connect to postgres with:

`psql -h localhost -U timetrex -W timetrex`

use "timetrex" as the password.  That should connect you do the database. You can then see if any tables have been created with a "\dt" command.

**Comment by koo9** [comment]
cannot connect, so the database is not created.

**Comment by apnar** [comment]
in the container what does "ps -ef" show?

**Comment by koo9** [comment]
![capture](https://user-images.githubusercontent.com/8421906/41882256-3181fa7c-78a5-11e8-8d3c-8f91a20b0b74.PNG)

**Comment by koo9** [comment]
it may every well be the windows networking with the linux image on hyperV.

**Comment by apnar** [comment]
Yep, not running.  It should have started automatically. You can try running "supervisorctl start postgresql" to see if that starts it.

If that doesn't work you can try running it by hand and see if you see any obvious errors:
`su - postgres`
`/usr/lib/postgresql/9.5/bin/postgres -c config_file=/etc/postgresql/9.5/main/postgresql.conf`

**Comment by koo9** [comment]
after running "supervisorctl start postgresql", seems like the database started. that might be the reason the db init failed.

running this "su - postgres /usr/lib/postgresql/9.5/bin/postgres -c config_file=/etc/postgresql/9.5/main/postgresql.conf" got no errors.

**Comment by koo9** [comment]
return the following scripts works. now can login with timetrex/timetrex

su - postgres -c "/usr/lib/postgresql/9.5/bin/initdb /database/" 
  su - postgres -c "psql -c \"CREATE USER timetrex WITH CREATEDB CREATEROLE LOGIN PASSWORD 'timetrex';\"; psql -c \"CREATE DATABASE timetrex;\"" &
  echo "New install detected!!!!"
  echo "Connect to http://[host]:[port]/timetrex/interface/install/install.php to finish installtion."

**Comment by koo9** [comment]
installation continue! thx!
